%YAML:1.0
server:
    url: mw.icat.vt.edu
    port: 9999

classes:
    oncam:
        username: admin
        password: admin
        path: video.cgi?.mjpg
    vivotek:
        username: root
        password: admin
        path: video.mjpg

cameras:
    - id: 1
      name: observation
      desc: Observation Room
      class: oncam
      ip: '192.168.1.14'
      crop: [50, 40, 450, 390]
      ang: 0
      spawns:
        - [370, 30, 90, 90]

    - id: 2
      name: learningA
      desc: Learning Lab A
      class: oncam
      ip: '192.168.1.15'
      crop: [70, 30, 900, 800]
      ang: 0

    - id: 3
      name: learningB
      desc: Learning Lab B
      class: oncam
      ip: '192.168.1.11'
      crop: [130, 260, 800, 550]
      ang: 0

    - id: 4
      name: learningC
      desc: Learning Lab C
      class: oncam
      ip: '192.168.1.10'
      crop: [130, 180, 800, 570]
      ang: 0

    - id: 5
      name: learningD
      desc: Learning Lab D
      class: oncam
      ip: '192.168.1.12'
      crop: [70, 25, 400, 330]
      ang: 0

    - id: 6
      name: hallwayA
      desc: Hallway A
      class: vivotek
      ip: '192.168.1.16'
      crop: [180, 90, 800, 800]
      ang: 0

    - id: 7
      name: hallwayB
      desc: Hallway B
      class: vivotek
      ip: '192.168.1.17'
      crop: [180, 240, 750, 650]
      ang: 0

    - id: 8
      name: hallwayC
      desc: Hallway C
      class: vivotek
      ip: '192.168.1.18'
      crop: [180, 250, 750, 650]
      ang: 0

    - id: 9
      name: hallwayD
      desc: Hallway D
      class: vivotek
      ip: '192.168.1.19'
      crop: [180, 250, 750, 800]
      ang: 0

    - id: 10
      name: hallwayE
      desc: Hallway E
      class: vivotek
      ip: '192.168.1.20'
      crop: [180, 250, 750, 726]
      ang: 0

    - id: 15
      name: secondFloor4thCam
      desc: secondFloor4thCam A
      class: oncam
      ip: '192.168.1.46'
      crop: [110, 60, 340, 350]
      ang: 0
      spawns:
        - [0, 0, 340, 20]
        - [0, 330, 340, 20]

    - id: 17
      name: HWOut2ndCamB
      desc: HWOut2ndCam B
      class: oncam
      ip: '192.168.1.44'
      crop: [40, 60, 410, 350]
      ang: 0
      spawns:
        - [80, 0, 230, 70]
        - [60, 290, 300, 60]

    - id: 29
      name: SandBxHallWay 2
      desc: SandBoxHallWay 2
      class: oncam
      ip: '192.168.1.34'
      crop: [150, 150, 800, 650]
      ang: -90

    - id: 30
      name: SandBoxHallWay 3
      desc: SandBoxHallWay 3
      class: oncam
      ip: '192.168.1.35'
      crop: [250, 200, 600, 550]      
      ang: -90

    - id: 31
      name: SandBoxHallWay 4
      desc: SandBoxHallWay 4
      class: oncam
      ip: '192.168.1.36'
      crop: [300, 200, 500, 550]
      ang: -90

    - id: 32
      name: SandBoxHallWay 5
      desc: SandBoxHallWay 5
      class: oncam
      ip: '192.168.1.37'
      crop: [250, 200, 530, 500]
      ang: -90

    - id: 33
      name: SandBoxHallWay 6
      desc: SandBoxHallWay 6
      class: oncam
      ip: '192.168.1.38'
      crop: [250, 200, 500, 550]
      ang: -90

    - id: 34
      name: SandBoxHallWay 7
      desc: SandBoxHallWay 7
      class: oncam
      ip: '192.168.1.39'
      crop: [250, 200, 530, 550]
      ang: -90

    - id: 50
      name: observation
      desc: Observation Room
      class: oncamTorg
      ip: '192.168.1.50'
      crop: [100, 100, 900, 700]
      ang: 0

    - id: 51
      name: observation
      desc: Observation Room
      class: oncamTorg
      ip: '192.168.1.51'
      crop: [100, 100, 900, 700]
      ang: 0

    - id: 56
      name: observation
      desc: Observation Room
      class: oncamTorg
      ip: '192.168.1.56'
      crop: [100, 100, 900, 700]
      ang: 0

    - id: 52
      name: observation
      desc: Observation Room
      class: oncam
      ip: '192.168.1.52'
      crop: [80, 100, 340, 300]
      ang: -90
      spawns:
        - [240, 5, 60, 45]

